# Generated by Django 5.0 on 2026-06-09 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('phone_number_id', models.CharField(max_length=100)),
                ('webhook_verify_token', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración WhatsApp',
                'verbose_name_plural': 'Configuraciones WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='PlantillaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recordatorio_3dias', 'Recordatorio 3 Días'), ('recordatorio_1dia', 'Recordatorio 1 Día'), ('vencimiento', 'Vencimiento'), ('multa', 'Multa Generada'), ('confirmacion', 'Confirmación Alquiler'), ('devolucion', 'Confirmación Devolución')], max_length=30, unique=True)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField(help_text='Variables: {nombre}, {numero_alquiler}, {fecha_fin}, {dias_restantes}, {monto}')),
                ('canal', models.CharField(choices=[('email', 'Correo Electrónico'), ('whatsapp', 'WhatsApp'), ('ambos', 'Ambos')], default='ambos', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'Correo Electrónico'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('fallida', 'Fallida'), ('leida', 'Leída')], default='pendiente', max_length=20)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='clientes.cliente')),
                ('plantilla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='notificaciones.plantillanotificacion')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
