# Generated by Django 5.0 on 2026-06-09 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntenciónBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('palabras_clave', models.JSONField(default=list)),
                ('respuesta_base', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Intención del Bot',
                'verbose_name_plural': 'Intenciones del Bot',
            },
        ),
        migrations.CreateModel(
            name='RespuestaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('intencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_rapidas', to='chatbot.intenciónbot')),
            ],
            options={
                'verbose_name': 'Respuesta Rápida',
                'verbose_name_plural': 'Respuestas Rápidas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SesionChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('canal', models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp')], default='web', max_length=20)),
                ('contexto', models.JSONField(blank=True, default=dict)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_chat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Chat',
                'verbose_name_plural': 'Sesiones de Chat',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('usuario', 'Usuario'), ('bot', 'Bot')], max_length=10)),
                ('contenido', models.TextField()),
                ('intencion', models.CharField(blank=True, max_length=100, null=True)),
                ('confianza', models.FloatField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chatbot.sesionchat')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['fecha_envio'],
            },
        ),
    ]
