# Generated by Django 5.0 on 2026-06-09 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alquileres', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_por_dia', models.DecimalField(decimal_places=2, default=50000, max_digits=10)),
                ('porcentaje_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dias_gracia', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Multa',
                'verbose_name_plural': 'Configuraciones de Multas',
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('dias_retraso', models.PositiveIntegerField(default=0)),
                ('valor_por_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('condonada', 'Condonada')], default='pendiente', max_length=20)),
                ('motivo_condonacion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='alquileres.alquiler')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='clientes.cliente')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PagoMulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='pagos/multas/')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('multa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='multas.multa')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_multas_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Multa',
                'verbose_name_plural': 'Pagos de Multas',
            },
        ),
    ]
