# Generated by Django 5.0 on 2026-06-09 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alquileres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField()),
                ('estado', models.CharField(choices=[('completa', 'Completa'), ('parcial', 'Parcial'), ('con_danos', 'Con Daños')], default='completa', max_length=20)),
                ('tiene_multa', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='alquileres.alquiler')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.PositiveIntegerField(default=1)),
                ('condicion', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('danado', 'Dañado'), ('perdido', 'Perdido')], default='bueno', max_length=20)),
                ('costo_dano', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descripcion_dano', models.TextField(blank=True, null=True)),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='devoluciones/')),
                ('detalle_alquiler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='alquileres.detallealquiler')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='devoluciones.devolucion')),
            ],
            options={
                'verbose_name': 'Detalle de Devolución',
                'verbose_name_plural': 'Detalles de Devolución',
            },
        ),
    ]
